from __future__ import annotations

import pytest

from kcat_rel.chemistry import formal_charge, generate_chemistry, grantham_distance
from kcat_rel.registry import FROZEN_PRIMARY_VARIANTS


REFERENCE_SEQUENCE = (
    "MGDSEMAVFGAAAPYLRKSEKERLEAQTRPFDLKKDVFVPDDKQEFVKAKIVSREGGKVTAETEYGKTVTVKEDQVMQQNPPKFDKIEDMAMLTFLHEPA"
    "VLYNLKDRYGSWMIYTYSGLFCVTVNPYKWLPVYTPEVVAAYRGKKRSEAPPHIFSISDNAYQYMLTDRENQSILITGESGAGKTVNTKRVIQYFAVIAA"
    "IGDRSKKDQSPGKGTLEDQIIQANPALEAFGNAKTVRNDNSSRFGKFIRIHFGATGKLASADIETYLLEKSRVIFQLKAERDYHIFYQILSNKKPELLDM"
    "LLITNNPYDYAFISQGETTVASIDDAEELMATDNAFDVLGFTSEEKNSMYKLTGAIMHFGNMKFKLKQREEQAEPDGTEEADKSAYLMGLNSADLLKGLC"
    "HPRVKVGNEYVTKGQNVQQVIYATGALAKAVYERMFNWMVTRINATLETKQPRQYFIGVLDIAGFEIFDFNSFEQLCINFTNEKLQQFFNHHMFVLEQEE"
    "YKKEGIEWTFIDFGMDLQACIDLIEKPMGIMSILEEECMFPKATDMTFKAKLFDNHLGKSANFQKPRNIKGKPEAHFSLIHYAGIVDYNIIGWLQKNKDP"
    "LNETVVGLYQKSSLKLLSTLFANYAGADAPIEKGKGKAKKGSSFQTVSALHRENLNKLMTNLRSTHPHFVRCIIPNETKSPGVMDNPLVMHQLRCNGVLE"
    "GIRICRKGFPNRILYGDFRQRYRILNPAAIPEGQFIDSRKGAEKLLSSLDIDHNQYKFGHTKVFFKAGLLGLLEEMRDERLSRIITRIQAQSRGVLARME"
    "YKKLLERRDSLLVIQWNIRAFMGVKNWPWMKLYFKIKPLLKSAEREKEMASMKEEFTRLKEALEKSEARRKELEEKMVSLLQEKNDLQLQVQAEQDNLAD"
    "AEERCDQLIKNKIQLEAKVKEMNERLEDEEEMNAELTAKKRKLEDECSELKRDIDDLELTLAKVEKEKHATENKVKNLTEEMAGLDEIIAKLTKEKKALQ"
    "EAHQQALDDLQAEEDKVNTLTKAKVKLEQQVDDLEGSLEQEKKVRMDLERAKRKLEGDLKLTQESIMDLENDKQQLDERLKKKDFELNALNARIEDEQAL"
    "GSQLQKKLKELQARIEELEEELEAERTARAKVEKLRSDLSRELEEISERLEEAGGATSVQIEMNKKREAEFQKMRRDLEEATLQHEATAAALRKKHADSV"
    "AELGEQIDNLQRVKQKLEKEKSEFKLELDDVTSNMEQIIKAKANLEKMCRTLEDQMNEHRSKAEETQRSVNDLTSQRAKLQTENGELSRQLDEKEALISQ"
    "LTRGKLTYTQQLEDLKRQLEEEVKAKNALAHALQSARHDCDLLREQYEEETEAKAELQRVLSKANSEVAQWRTKYETDAIQRTEELEEAKKKLAQRLQEA"
    "EEAVEAVNAKCSSLEKTKHRLQNEIEDLMVDVERSNAAAAALDKKQRNFDKILAEWKQKYEESQSELESSQKEARSLSTELFKLKNAYEESLEHLETFKR"
    "ENKNLQEEISDLTEQLGSSGKTIHELEKVRKQLEAEKMELQSALEEAEASLEHEEGKILRAQLEFNQIKAEIERKLAEKDEEMEQAKRNHLRVVDSLQTS"
    "LDAETRSRNEALRVKKKMEGDLNEMEIQLSHANRMAAEAQKQVKSLQSLLKDTQIQLDDAVRANDDLKENIAIVERRNNLLQAELEELRAVVEQTERSRK"
    "LAEQELIETSERVQLLHSQNTSLINQKKKMDADLSQLQTEVEEAVQECRNAEEKAKKAITDAAMMAEELKKEQDTSAHLERMKKNMEQTIKDLQHRLDEA"
    "EQIALKGGKKQLQKLEARVRELENELEAEQKRNAESVKGMRKSERRIKELTYQTEEDRKNLLRLQDLVDKLQLKVKAYKRQAEEAEEQANTNLSKFRKVQ"
    "HELDEAEERADIAESQVNKLRAKSRDIGTKGLNEE"
)


def test_frozen_charge_and_grantham_conventions() -> None:
    assert formal_charge("H") == 0
    assert formal_charge("D") == -1
    assert formal_charge("R") == 1
    assert grantham_distance("I", "L") == 5
    assert grantham_distance("C", "W") == 215
    assert grantham_distance("W", "C") == 215


def test_chemistry_is_complete_label_blind_and_ordered() -> None:
    table = generate_chemistry(FROZEN_PRIMARY_VARIANTS, REFERENCE_SEQUENCE)

    assert tuple(table.variant) == FROZEN_PRIMARY_VARIANTS
    assert tuple(table.columns) == ("variant", "delta_charge", "grantham_distance")
    assert tuple(table.delta_charge) == (0, 1, -1, 0, -1, -1, 0, 0, -1, -1, 1, 1, 1, 0, 0, 0, 0)
    assert tuple(table.grantham_distance) == (
        83,
        23,
        43,
        68,
        43,
        180,
        89,
        45,
        29,
        101,
        125,
        125,
        152,
        98,
        46,
        58,
        22,
    )
    assert not table.isna().any().any()


def test_chemistry_rejects_any_primary_cohort_amendment() -> None:
    with pytest.raises(ValueError, match="frozen primary cohort"):
        generate_chemistry(("A115H", *FROZEN_PRIMARY_VARIANTS[1:]), REFERENCE_SEQUENCE)


@pytest.mark.parametrize("residue", ["B", "", "AA"])
def test_charge_and_distance_reject_nonstandard_residues(residue: str) -> None:
    with pytest.raises(ValueError, match="non-standard"):
        formal_charge(residue)
    with pytest.raises(ValueError, match="non-standard"):
        grantham_distance("A", residue)
